#!/usr/bin/env python3
"""Create parent and sub-issues for skill review suggestions.

This script reads the skill-suggestions.json file generated by
generate_skill_review_report.py and creates GitHub issues:
- One parent issue tracking all skill improvements
- One sub-issue per skill with specific improvement suggestions

Requires: gh CLI with authentication (GH_TOKEN environment variable)
"""

import json
import re
import subprocess
import sys
import time
from pathlib import Path


def run_gh_command(args: list[str], check: bool = True) -> str:
    """Run a gh CLI command and return stdout."""
    result = subprocess.run(
        ["gh"] + args,
        capture_output=True,
        text=True,
        check=False,
    )
    if check and result.returncode != 0:
        print(f"Error running gh {' '.join(args)}: {result.stderr}", file=sys.stderr)
        raise subprocess.CalledProcessError(result.returncode, args, result.stdout, result.stderr)
    return result.stdout.strip()


def find_existing_issue(title: str, label: str = "copilot") -> int | None:
    """Search for an existing open issue with the given title."""
    output = run_gh_command([
        "issue", "list",
        "--state", "open",
        "--label", label,
        "--search", f'in:title "{title}"',
        "--json", "number,title",
    ], check=False)
    
    if not output:
        return None
    
    try:
        issues = json.loads(output)
        for issue in issues:
            if issue.get("title") == title:
                return issue.get("number")
    except json.JSONDecodeError:
        pass
    
    return None


def create_issue(title: str, body: str, label: str = "copilot") -> int:
    """Create a GitHub issue and return its number."""
    output = run_gh_command([
        "issue", "create",
        "--title", title,
        "--body", body,
        "--label", label,
    ])
    # Extract issue number from URL using regex for reliability
    # URL format: https://github.com/owner/repo/issues/123
    match = re.search(r"/issues/(\d+)$", output)
    if match:
        return int(match.group(1))
    # Fallback: try to extract last numeric segment
    match = re.search(r"(\d+)\s*$", output)
    if match:
        return int(match.group(1))
    raise ValueError(f"Could not extract issue number from: {output}")


def edit_issue(issue_number: int, body: str) -> None:
    """Update the body of an existing issue."""
    run_gh_command([
        "issue", "edit",
        str(issue_number),
        "--body", body,
    ])


def comment_on_issue(issue_number: int, comment: str) -> None:
    """Add a comment to an issue."""
    run_gh_command([
        "issue", "comment",
        str(issue_number),
        "--body", comment,
    ])


def main() -> None:
    suggestions_path = Path("reports/skill-suggestions.json")
    if not suggestions_path.exists():
        print(f"Error: {suggestions_path} not found", file=sys.stderr)
        sys.exit(1)

    skill_suggestions = json.loads(suggestions_path.read_text(encoding="utf-8"))
    
    if not skill_suggestions:
        print("No skill suggestions found. Exiting.")
        sys.exit(0)

    parent_title = "chore: skill improvements from scheduled review"
    
    # Check for existing parent issue to avoid duplicates
    existing_parent = find_existing_issue(parent_title)
    if existing_parent:
        print(f"Parent issue #{existing_parent} already exists. Skipping creation.")
        sys.exit(0)

    # Create parent issue with placeholder body
    parent_body = """This issue tracks improvements to code review skill instructions identified by the weekly automated review.

**Goal:** Improve the quality and clarity of skill instructions used by AI coding agents for code review.

## Sub-issues

_Sub-issues will be listed below after creation._"""

    parent_number = create_issue(parent_title, parent_body)
    print(f"Created parent issue #{parent_number}")

    # Create sub-issues for each skill
    sub_issue_refs: list[str] = []
    
    for skill_name, suggestions in sorted(skill_suggestions.items()):
        skill_title = f"Improve {skill_name} skill – scheduled review"
        
        # Check for existing sub-issue to avoid duplicates
        existing_sub = find_existing_issue(skill_title)
        if existing_sub:
            print(f"Sub-issue for {skill_name} (#{existing_sub}) already exists. Skipping.")
            sub_issue_refs.append(f"- [ ] #{existing_sub} {skill_title}")
            continue

        # Create sub-issue body
        sub_body = f"""<!-- scheduled-skill-review:{skill_name} -->

Apply the following improvements to `skills/{skill_name}/SKILL.md`:

{suggestions}

---

Parent issue: #{parent_number}"""

        sub_number = create_issue(skill_title, sub_body)
        print(f"Created sub-issue #{sub_number} for {skill_name}")
        sub_issue_refs.append(f"- [ ] #{sub_number} {skill_title}")
        
        # Small delay to avoid rate limiting
        time.sleep(1)

    # Update parent issue body with sub-issue references
    sub_issues_list = "\n".join(sub_issue_refs)
    updated_parent_body = f"""This issue tracks improvements to code review skill instructions identified by the weekly automated review.

**Goal:** Improve the quality and clarity of skill instructions used by AI coding agents for code review.

## Sub-issues

{sub_issues_list}"""

    edit_issue(parent_number, updated_parent_body)
    print(f"Updated parent issue #{parent_number} with sub-issue references")

    # Comment on parent issue to trigger Copilot agent
    comment_on_issue(parent_number, "@copilot")
    print("Commented on parent issue to trigger Copilot agent")


if __name__ == "__main__":
    main()
